# Generated by Django 5.1.6 on 2025-03-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('servapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('RE', 'Resort'), ('WP', 'Waterpark'), ('DP', 'Destination_packages'), ('DB', 'Dhaba'), ('VI', 'Villas'), ('GO', 'Game_On')], max_length=2)),
                ('service_image', models.ImageField(upload_to='service')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
