# Generated by Django 5.1.6 on 2025-03-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TSBv1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
    ]
