# Generated by Django 5.1.6 on 2025-03-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSBv1', '0002_remove_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(upload_to='service/'),
        ),
    ]
