# Generated by Django 5.1.6 on 2025-04-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TSBv1', '0006_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Payment',
            new_name='payment',
        ),
    ]
