# Generated by Django 5.2.8 on 2025-11-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSBv1', '0007_rename_payment_orderplaced_payment'),
    ]

    def copy_service_images(apps, schema_editor):
        Services = apps.get_model('TSBv1', 'Services')
        ServiceImage = apps.get_model('TSBv1', 'ServiceImage')
        for service in Services.objects.all():
            image = getattr(service, 'service_image', None)
            if image:
                ServiceImage.objects.create(service=service, image=image)

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TSBv1.services')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(copy_service_images, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='services',
            name='service_image',
        ),
    ]
