# Generated by Django 4.1.13 on 2025-12-31 08:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TSBv1', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='is_advance_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 31, 8, 3, 33, 663088, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('ADVANCE', 'Advance Payment'), ('REMAINING', 'Remaining Payment')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='services',
            name='advance_payment_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=10),
        ),
        migrations.AddField(
            model_name='services',
            name='advance_payment_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount in INR or percentage (0-100)', max_digits=10),
        ),
        migrations.AddField(
            model_name='services',
            name='supports_advance_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdvanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('qr_hash', models.CharField(max_length=64, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking_date', models.DateField(help_text='Date for which the booking is made')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='Booking expiration time')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified - Entry Allowed'), ('USED', 'Already Used'), ('EXPIRED', 'Booking Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('verified_by_staff', models.CharField(blank=True, max_length=100)),
                ('verification_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('advance_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_bookings', to='TSBv1.payment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSBv1.customer')),
                ('final_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_bookings', to='TSBv1.payment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSBv1.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='advancebooking',
            index=models.Index(fields=['booking_code'], name='TSBv1_advan_booking_62bf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='advancebooking',
            index=models.Index(fields=['status', 'valid_until'], name='TSBv1_advan_status_e6beb6_idx'),
        ),
        migrations.AddIndex(
            model_name='advancebooking',
            index=models.Index(fields=['booking_date'], name='TSBv1_advan_booking_48896d_idx'),
        ),
    ]
