# Generated by Django 3.2.25 on 2025-12-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSBv1', '0010_orderplaced_is_advance_order_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancebooking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={},
        ),
        migrations.AlterField(
            model_name='advancebooking',
            name='qr_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
