# Generated by Django 3.2.25 on 2026-03-18 08:16

import TSBv1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSBv1', '0011_auto_20251231_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('alt_text', models.CharField(default='Hero slide', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
