"""
changes for github
Django settings for TSB project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
--------SOCKET---------
[Unit]
Description=gunicorn socket

[Socket]
ListenStream=/run/gunicorn.sock

[Install]
WantedBy=sockets.target
-----------------
--------SERVICE---------
[Unit]
Description=gunicorn daemon for TSB
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/TSBEnterprises/TSB
ExecStart=/home/ubuntu/TSB/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/home/ubuntu/TSBEnterprises/TSB/TSB/TSB.sock TSB.wsgi:application

[Install]
WantedBy=multi-user.target
-----------------
"""
import os
from pathlib import Path
from urllib.parse import urlparse
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'TSB.settings')

SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY')
SUPABASE_MEDIA_BUCKET = os.getenv('SUPABASE_MEDIA_BUCKET', 'media')
SUPABASE_MEDIA_PUBLIC = os.getenv('SUPABASE_MEDIA_PUBLIC', 'true').lower() in {'1', 'true', 'yes', 'on'}
SUPABASE_MEDIA_PUBLIC_URL = os.getenv('SUPABASE_MEDIA_PUBLIC_URL')
SUPABASE_SIGNED_URL_EXPIRY = int(os.getenv('SUPABASE_SIGNED_URL_EXPIRY', '3600'))

if SUPABASE_URL and not SUPABASE_MEDIA_PUBLIC_URL:
    SUPABASE_MEDIA_PUBLIC_URL = f"{SUPABASE_URL.rstrip('/')}/storage/v1/object/public/{SUPABASE_MEDIA_BUCKET}"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qpe%*dykwr5(whjwqero3rv)v*h7o8!_i1o=a@n3+i^j$&y0bi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
#'15.206.90.130'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'TSBv1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TSB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'TSBv1', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TSB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Get DATABASE_URL from environment variable (REQUIRED for Supabase PostgreSQL)
DATABASE_URL = os.getenv('DATABASE_URL')

# Use SQLite for local development if DATABASE_URL is not set or connection fails
if not DATABASE_URL:
    # Fallback to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Parse the DATABASE_URL (Supabase PostgreSQL connection string)
    # Format: postgresql://user:password@host:port/database
    try:
        import socket
        db_url = urlparse(DATABASE_URL)
        # Force IPv4 by resolving hostname
        hostname = db_url.hostname
        try:
            ipv4_addr = socket.getaddrinfo(hostname, None, socket.AF_INET)[0][4][0]
            resolved_host = ipv4_addr
        except:
            resolved_host = hostname
        
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_url.path[1:],  # Remove leading '/'
                'USER': db_url.username,
                'PASSWORD': db_url.password,
                'HOST': resolved_host,
                'PORT': db_url.port or '5432',
                'OPTIONS': {
                    'connect_timeout': 10,
                    'sslmode': 'require',
                },
            }
        }
    except Exception as e:
        # If connection fails, fallback to SQLite for local development
        print(f"Warning: Could not connect to PostgreSQL database: {e}")
        print("Falling back to SQLite for local development...")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')
LOGIN_REDIRECT_URL = '/profile/'

if SUPABASE_URL and SUPABASE_SERVICE_KEY:
    STORAGES = {
        "default": {
            "BACKEND": "TSB.storage_backends.SupabaseMediaStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_ROOT = None
    if SUPABASE_MEDIA_PUBLIC_URL:
        MEDIA_URL = SUPABASE_MEDIA_PUBLIC_URL


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

razor_pay_key_id = 'rzp_live_ZWQJtI7AM0kdlA'
key_secret = 'W7MYw65yiAkUL6A2dKUtLn6R'
